### ISSUE TITLE
RSB deactivation delay

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/jul#29]
RSB takes to much time during deactivation! This causes into bad bco shutdown delays.

test example: `RSBCommunicationServiceTest.class` -> `testReconnection`

**Comment by pLeminoq** [comment]
While testing for issue #42 I found that often a delay in this test is produced because it does not shutdown properly. The GlobalCachedExecutionService has to switch to its hard shutdown. I identified that a ping task from the remote is still running and not cancelled when it should be but could not find why yet.

**Comment by pLeminoq** [comment]
I think this has already been fixed. If not reopen.
