### ISSUE TITLE
API changes analysis report for JUL Storage

### ISSUE THREAD

**Issue by lvc** [openbase/jul#39]
Hi,

I'd like to share report on API changes and backward compatibility for the JUL Storage library: https://abi-laboratory.pro/java/tracker/timeline/jul.storage/

The report is generated according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2 by the https://github.com/lvc/japi-tracker tool.

Hope it will be helpful for users and maintainers of the library.

Please let me know if you'd like to see reports for any other Java modules in the tracker.

Thank you.

![jul storage-1](https://user-images.githubusercontent.com/1517837/32362150-32a9606a-c078-11e7-8d27-232f70824ab2.png)

![jul storage-2](https://user-images.githubusercontent.com/1517837/32362149-327e8dae-c078-11e7-9900-1f33c153ec7f.png)

**Comment by DivineThreepwood** [comment]
Hey lvc,

thank you very much for such a nice service and sorry for my late response. You just catched me in a really busy time phase and after that the issue was out of my mind. 

Do you even support maven multi modules? Because your analysis is just performed for one single submodule of jul. I would totally love to register you tracker for all jul submodules and as well for attaching the tracker to the bco.dal subprojects as well (github.com/openbase/bco.dal). 

Actually I was already looking for such an API validator a couple of times because without it's really a challenge to avoiding incompatibilities between different releases within the same major version range.

Do you plan any investigations to build a github plugin out of your tool? This would spread your service in a much more comfortable way. 

Cheers!
Marian

**Comment by DivineThreepwood** [comment]
cleanup outdated issue.
