### ISSUE TITLE
ProtobufFileProcessor fails in serializing types containing ByteArrays

### ISSUE THREAD

**Issue by pLeminoq** [openbase/jul#56]
As part of the CredentialStore change the LoginCredentials type now directly contains a ByteArray instead of a string. However, when testing this revealed an issue with the ProtobufFileProcessor. I added a ProtobufFileProcessorTest in commit 610498ae7ac29b32e756c70ceee103c99a717f0d which demonstrates the issue.

**Comment by DivineThreepwood** [comment]
The issue seems to be related to the ```private byte[] hash(String toHash)``` method and not to the ```ProtobufFileProcessor```. Here you are using a UTF_8 String representation ```toHash.getBytes(StandardCharsets.UTF_8)``` but filling up missing bits with zeros till 16 bit ```Arrays.copyOf(key, 16)```(this is at least what the copy method is doing in case the input is shorter than 16 bit). In my view this causes the issue when deserializing the bytes into a UTF_8 String representation where the zero suffix is interpreted as a different char. So just make sure the array is copped into its right pieces. Two solutions would be possible:
<pre>
private byte[] hash(String toHash) throws Exception {
        byte[] key = toHash.getBytes(StandardCharsets.UTF_8);
        String HASH_ALGORITHM = "SHA-256";
        MessageDigest sha = MessageDigest.getInstance(HASH_ALGORITHM);
        key = sha.digest(key);
        //return key;
        System.out.println("length["+sha.getDigestLength()+"]");
        return Arrays.copyOf(key, 8);
    }
</pre>

or

<pre>
private byte[] hash(String toHash) throws Exception {
        byte[] key = toHash.getBytes(StandardCharsets.UTF_16);
        String HASH_ALGORITHM = "SHA-256";
        MessageDigest sha = MessageDigest.getInstance(HASH_ALGORITHM);
        key = sha.digest(key);
        //return key;
        System.out.println("length["+sha.getDigestLength()+"]");
        return Arrays.copyOf(key, 16);
    }
</pre>

**Comment by DivineThreepwood** [comment]
Please close if this solves the issue.

**Comment by DivineThreepwood** [comment]
fix applied in branch ```feature-credential-store-update```
